name: frontend
description: HireIQ - AI Interview Prep Platform
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  video_player: ^2.8.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  dio: ^5.4.0
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.0.0
  file_picker: ^8.0.7
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  audioplayers: ^5.2.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.0 # ← NEW: runtime permissions for mic
  intl: ^0.20.2
  web: ^0.5.1
  url_launcher: ^6.2.5
  google_sign_in: ^7.2.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
