"""add question bank

Revision ID: 0c9db949a971
Revises: 
Create Date: 2026-02-20 21:00:26.352898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9db949a971'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('job_role', sa.String(length=255), nullable=True),
    sa.Column('follow_ups', sa.JSON(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('sample_answer', sa.Text(), nullable=True),
    sa.Column('is_community', sa.Boolean(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.alter_column('interview_messages', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interview_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('interview_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('interviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interviews', 'job_role',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'interviews', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.alter_column('interviews', 'job_role',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('interviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interview_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('interview_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('interview_messages', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    # ### end Alembic commands ###
